### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by iggregiee**
Group Repo Assignment Info.

### CODE REVIEW

**Comment by iggregiee** [comment]
Hey Guys Look over my separate branch in regards to the readme.md and contributing.md and let me know if there are other things to add? This is in the Mikey Branch waiting to be Merged and approved by the group before merging to the main. 
Please look it over and reply to me and tell me what else I should add to the repo

**Comment by Mysticgwen** [comment]
I'm not into your full edit of the contribution.md, why didn't you volunteer to-do it when it was agreed I would do it? Furthermore, this is a class & a group project- the formalities seem very broad and unnecessary, Mike.

**Comment by iggregiee** [comment]
Hey Lynette, Please Quote what parts of the MD you don't agree with and elaborate more one what we could do to add more of everyone's input in the repo. This is a group project yes, but we also got to hold each other accountable for what we contribute in. 

We could also include in the contributing.md how to engage in discussion around what each of us is assigned to do. When looking into the files we need to come to agreement in the context of the files being created and uploaded. 

Also, tell me what part about the contributing you don't like and what could be changed but this is a team effort so we get to play around with the content of the text and find middle ground in the overall look of the file/page.

**Comment by Mysticgwen** [comment]
Mike,

As stated in prior comment here today: "I'm not into your full edit of the contribution.md, why didn't you volunteer to-do it when it was agreed I would do it? Furthermore, this is a class & a group project- the formalities seem very broad and unnecessary, Mike." 

In other words, this is a project for class with a group - two of whom are novices(admittedly) & 1 of whom has an extensive legal background due a multiple times convicted stalker and abuser and/or former officers of the court who violated the laws, got sued and/or took it upon themselves to remove themselves from the registries they were on and/or to resign from the work they failed at doing- IE - I am not interested in a contribution. MD with clauses in how to communicate, what to-do, and/or needing to reference a document that was agreed 👍 I would write ✍️ (due to this very thing, I assumed you'd want this sort of contribution.md due to your choice of license & template).

My contribution.md stated/states we're a democracy.  Not to be a jerk. And, was written so that our team could collaborate in a casual learning environment, where creating individually isn't only encouraged but a mandate - particularly without additional instructions than the assignments actual rubric. 

I can assume based on your pattern of behavior since Saturday (the 21st) that this entire redo that I do not agree to in anyway - will be pushed through because Khang is happy to have you tell us what to-do.

I draw a hard line on contracts- including readme, the license, and contribution.md. 

I'd be willing to compromise and let you keep project 1 (history of Microsoft you've also been insisting on) but I'm not going to legally agree to this contribution.md and I don't want to be listed as a contribution if you continue to push this ongoing insistence on being in control of that which I volunteered for - to avoid this.

I have a 3.5 cumulative GPA, every group project I have been in has been an A.

Mike, you're clearly in advanced coder - based on your terminology and ease of use. This class had/has no prerequisites but, it's important we all contribute without you needing to approve everything and/or having you scrap/erase/send emails until you get what you want while deflecting and sending messages restating things and not acknowledging what's written to you (repeatedly).

**Comment by iggregiee** [comment]
Lynette where are you getting all of this hostile rhetoric coming from. Nothing is even pushed or merged yet into the main branch which still has YOUR contributing.md where your Contributing.md needs edits and changes to reflect EVERYONES input. This is a separate branch and I'm asking you to review the code. Not attack me and be rude in any which way. In regards to reflecting on this, I don't condone your behavior in trying to reframe the situation to where I'm neglecting your effort. I'm trying to make the required edits and looks so that the contributing.md file has EVERYONE inputting; not just what you say and that's how it goes. Just because you agree to doing a certain part of the project doesn't mean you get to disregard the consideration of anyone their input in the main branch. That's why we have separate branches. to work on and review each others documentation and see what fits and what doesn't before agreeing AS A TEAM to merge the main branch. 


You understand this conflict is because you decided to not wait for any answer from the group about the group repo and SOLEY decided to create another repo (which made no sense because Khang is able to make contributions fine) and then try to force everyone to join the repo you created which was adding another step. Also, you refused to answer my troubleshooting questions where I asked if you are able to make changes now and refused and just reposted your adamant proposal of joining the 3rd group repo when that's not what the group agreed on... 

We can talk to Bob about this But I think you are coming at me and harassing me for no reason regarding this conflict when I just want resolve and to work as a group.

**Review by ReneMunozH — APPROVED** [review]

**Review by Khangdo201 — APPROVED** [review]
thanks for adding my part into Contributing.md Mike

**Comment by iggregiee** [comment]
SO we will erge

**Pull request closed without merging**
